const BOARD_ROW = 15;
const BOARD_COLUMN = 15;
const BOARD_SIZE = BOARD_ROW * BOARD_COLUMN;
const NUMBER_OF_LEAF = 6;
const NUMBER_OF_BRANCH = 30;
const YELLOW = "#f9e35f";
const RED =  "#f95151";
const GREEN = "#0b6623";
const BROWN = "#72601b";
const LEFT = 'LEFT';
const RIGHT = 'RIGHT';
const NORTH = 'NORTH';
const EAST = 'EAST';
const SOUTH = 'SOUTH';
const WEST = 'WEST';

export { BOARD_SIZE, BOARD_ROW, BOARD_COLUMN, NUMBER_OF_LEAF, NUMBER_OF_BRANCH,
     YELLOW, RED, GREEN, BROWN, LEFT, RIGHT, NORTH, EAST, SOUTH, WEST }